import java.io.*;
import java.util.Random;
import java.util.Scanner;

class QuickSort {
    static int max = 5000;

    void quicksort(int a[], int low, int high) {
        int s;
        if (low < high) {
            s = partition(a, low, high);
            quicksort(a, low, s - 1);
            quicksort(a, s + 1, high);
        }
    }

    int partition(int a[], int low, int high) {
        int p, i, j, temp;
        p = a[low];
        i = low + 1;
        j = high;
        while (low < high) {
            while (a[i] <= p && i < high)
                i++;
            while (a[j] > p)
                j--;
            if (i < j) {
                temp = a[i];
                a[i] = a[j];
                a[j] = temp;
            } else {
                temp = a[low];
                a[low] = a[j];
                a[j] = temp;
                return j;
            }
        }
    }

public static void main(String args[])
{
int a[], i, n;
Scanner sc =new Scanner(System.in);
System.out.println("Enter the Number of elements to be sorted");
 n=sc.nextInt();
a= new int[max];
Random generator=new Random();
for(i=0; i<n; i++)
{
a[i]=generator.nextInt(50);
}
System.out.println("The Inputs generated by Random Number Generate are: ");
for(i=0; i<n; i++)
System.out.print(a[i]+"\t");
long startTime=System.nanoTime();
time QuickSortqs = new QuickSort();
qs.quicksort(a,0,n-1);
long stopTime=System.nanoTime();
long elapseTime=(stopTime-startTime);
System.out.println();
System.out.println("Sorted array is");
for(i=0;i<n;i++)
System.out.print(a[i]+"\t");
System.out.println();
System.out.println("Time taken to sort given array is: "+elapseTime+" nano seconds");
}
}
